# Server
server.port=8085

# PostgreSQL (Supabase)
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?prepareThreshold=0
spring.datasource.username=postgres.lcwywqhzfwsjqnusvbhw
spring.datasource.password=PAF@2026@SLIIT
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Supabase Storage
supabase.url=https://lcwywqhzfwsjqnusvbhw.supabase.co
supabase.service-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxjd3l3cWh6ZndzanFudXN2Ymh3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NTQ2NDY0MiwiZXhwIjoyMDkxMDQwNjQyfQ.c-9qL0HPXMucLI3KhpcoEhyCKAC9_WmCqa6rRjAEDok

# Supabase JWT (add this - needed for your auth module)
supabase.jwt-secret=sb_secret_fKmF2j-TxLMRHsijepEdXw_w8TqKUzU

# Multipart file upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB

# CORS
cors.allowed-origins=http://localhost:5173,http://localhost:3000