# Server
server.port=8085

# Actual Supabase PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://db.lcwywqhzfwsjqnusvbhw.supabase.co:5432/postgres
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=PAF@2026@SLIIT

# Important: Tell Spring Boot not to wipe your cloud database on startup
spring.jpa.hibernate.ddl-auto=update


# H2 Console (useful for debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.root=INFO
logging.level.com.smartcampus=DEBUG

supabase.url=https://lcwywqhzfwsjqnusvbhw.supabase.co
supabase.key=your-anon-key-here
supabase.storage.bucket=attachments
supabase.service-key=your-service-role-key-here